package playground

// Code generated by /Users/bingjia.chen/.asdf/installs/golang/1.20/go/bin/peg -switch -inline -strict -output ./grammar.go grammar.peg DO NOT EDIT.

import (
	"fmt"
	"io"
	"os"
	"sort"
	"strconv"
	"strings"
)

const endSymbol rune = 1114112

/* The rule types inferred from the grammar are below. */
type pegRule uint8

const (
	ruleUnknown pegRule = iota
	ruleScript
	ruleEOF
	ruleValue
	ruleIntegerLiteral
	ruleHexNumeral
	ruleHexDigit
	ruleDecimalNumeral
)

var rul3s = [...]string{
	"Unknown",
	"Script",
	"EOF",
	"Value",
	"IntegerLiteral",
	"HexNumeral",
	"HexDigit",
	"DecimalNumeral",
}

type token32 struct {
	pegRule
	begin, end uint32
}

func (t *token32) String() string {
	return fmt.Sprintf("\x1B[34m%v\x1B[m %v %v", rul3s[t.pegRule], t.begin, t.end)
}

type node32 struct {
	token32
	up, next *node32
}

func (node *node32) print(w io.Writer, pretty bool, buffer string) {
	var print func(node *node32, depth int)
	print = func(node *node32, depth int) {
		for node != nil {
			for c := 0; c < depth; c++ {
				fmt.Fprintf(w, " ")
			}
			rule := rul3s[node.pegRule]
			quote := strconv.Quote(string(([]rune(buffer)[node.begin:node.end])))
			if !pretty {
				fmt.Fprintf(w, "%v %v\n", rule, quote)
			} else {
				fmt.Fprintf(w, "\x1B[36m%v\x1B[m %v\n", rule, quote)
			}
			if node.up != nil {
				print(node.up, depth+1)
			}
			node = node.next
		}
	}
	print(node, 0)
}

func (node *node32) Print(w io.Writer, buffer string) {
	node.print(w, false, buffer)
}

func (node *node32) PrettyPrint(w io.Writer, buffer string) {
	node.print(w, true, buffer)
}

type tokens32 struct {
	tree []token32
}

func (t *tokens32) Trim(length uint32) {
	t.tree = t.tree[:length]
}

func (t *tokens32) Print() {
	for _, token := range t.tree {
		fmt.Println(token.String())
	}
}

func (t *tokens32) AST() *node32 {
	type element struct {
		node *node32
		down *element
	}
	tokens := t.Tokens()
	var stack *element
	for _, token := range tokens {
		if token.begin == token.end {
			continue
		}
		node := &node32{token32: token}
		for stack != nil && stack.node.begin >= token.begin && stack.node.end <= token.end {
			stack.node.next = node.up
			node.up = stack.node
			stack = stack.down
		}
		stack = &element{node: node, down: stack}
	}
	if stack != nil {
		return stack.node
	}
	return nil
}

func (t *tokens32) PrintSyntaxTree(buffer string) {
	t.AST().Print(os.Stdout, buffer)
}

func (t *tokens32) WriteSyntaxTree(w io.Writer, buffer string) {
	t.AST().Print(w, buffer)
}

func (t *tokens32) PrettyPrintSyntaxTree(buffer string) {
	t.AST().PrettyPrint(os.Stdout, buffer)
}

func (t *tokens32) Add(rule pegRule, begin, end, index uint32) {
	tree, i := t.tree, int(index)
	if i >= len(tree) {
		t.tree = append(tree, token32{pegRule: rule, begin: begin, end: end})
		return
	}
	tree[i] = token32{pegRule: rule, begin: begin, end: end}
}

func (t *tokens32) Tokens() []token32 {
	return t.tree
}

type parser struct {
	Buffer string
	buffer []rune
	rules  [8]func() bool
	parse  func(rule ...int) error
	reset  func()
	Pretty bool
	tokens32
}

func (p *parser) Parse(rule ...int) error {
	return p.parse(rule...)
}

func (p *parser) Reset() {
	p.reset()
}

type textPosition struct {
	line, symbol int
}

type textPositionMap map[int]textPosition

func translatePositions(buffer []rune, positions []int) textPositionMap {
	length, translations, j, line, symbol := len(positions), make(textPositionMap, len(positions)), 0, 1, 0
	sort.Ints(positions)

search:
	for i, c := range buffer {
		if c == '\n' {
			line, symbol = line+1, 0
		} else {
			symbol++
		}
		if i == positions[j] {
			translations[positions[j]] = textPosition{line, symbol}
			for j++; j < length; j++ {
				if i != positions[j] {
					continue search
				}
			}
			break search
		}
	}

	return translations
}

type parseError struct {
	p   *parser
	max token32
}

func (e *parseError) Error() string {
	tokens, err := []token32{e.max}, "\n"
	positions, p := make([]int, 2*len(tokens)), 0
	for _, token := range tokens {
		positions[p], p = int(token.begin), p+1
		positions[p], p = int(token.end), p+1
	}
	translations := translatePositions(e.p.buffer, positions)
	format := "parse error near %v (line %v symbol %v - line %v symbol %v):\n%v\n"
	if e.p.Pretty {
		format = "parse error near \x1B[34m%v\x1B[m (line %v symbol %v - line %v symbol %v):\n%v\n"
	}
	for _, token := range tokens {
		begin, end := int(token.begin), int(token.end)
		err += fmt.Sprintf(format,
			rul3s[token.pegRule],
			translations[begin].line, translations[begin].symbol,
			translations[end].line, translations[end].symbol,
			strconv.Quote(string(e.p.buffer[begin:end])))
	}

	return err
}

func (p *parser) PrintSyntaxTree() {
	if p.Pretty {
		p.tokens32.PrettyPrintSyntaxTree(p.Buffer)
	} else {
		p.tokens32.PrintSyntaxTree(p.Buffer)
	}
}

func (p *parser) WriteSyntaxTree(w io.Writer) {
	p.tokens32.WriteSyntaxTree(w, p.Buffer)
}

func (p *parser) SprintSyntaxTree() string {
	var bldr strings.Builder
	p.WriteSyntaxTree(&bldr)
	return bldr.String()
}

func Pretty(pretty bool) func(*parser) error {
	return func(p *parser) error {
		p.Pretty = pretty
		return nil
	}
}

func Size(size int) func(*parser) error {
	return func(p *parser) error {
		p.tokens32 = tokens32{tree: make([]token32, 0, size)}
		return nil
	}
}
func (p *parser) Init(options ...func(*parser) error) error {
	var (
		max                  token32
		position, tokenIndex uint32
		buffer               []rune
	)
	for _, option := range options {
		err := option(p)
		if err != nil {
			return err
		}
	}
	p.reset = func() {
		max = token32{}
		position, tokenIndex = 0, 0

		p.buffer = []rune(p.Buffer)
		if len(p.buffer) == 0 || p.buffer[len(p.buffer)-1] != endSymbol {
			p.buffer = append(p.buffer, endSymbol)
		}
		buffer = p.buffer
	}
	p.reset()

	_rules := p.rules
	tree := p.tokens32
	p.parse = func(rule ...int) error {
		r := 1
		if len(rule) > 0 {
			r = rule[0]
		}
		matches := p.rules[r]()
		p.tokens32 = tree
		if matches {
			p.Trim(tokenIndex)
			return nil
		}
		return &parseError{p, max}
	}

	add := func(rule pegRule, begin uint32) {
		tree.Add(rule, begin, position, tokenIndex)
		tokenIndex++
		if begin != position && position > max.end {
			max = token32{rule, begin, position}
		}
	}

	matchDot := func() bool {
		if buffer[position] != endSymbol {
			position++
			return true
		}
		return false
	}

	/*matchChar := func(c byte) bool {
		if buffer[position] == c {
			position++
			return true
		}
		return false
	}*/

	/*matchRange := func(lower byte, upper byte) bool {
		if c := buffer[position]; c >= lower && c <= upper {
			position++
			return true
		}
		return false
	}*/

	_rules = [...]func() bool{
		nil,
		/* 0 Script <- <(Value EOF)> */
		func() bool {
			position0, tokenIndex0 := position, tokenIndex
			{
				position1 := position
				{
					position2 := position
					{
						position3 := position
						{
							position4, tokenIndex4 := position, tokenIndex
							{
								position6, tokenIndex6 := position, tokenIndex
								if buffer[position] != rune('+') {
									goto l7
								}
								position++
								goto l6
							l7:
								position, tokenIndex = position6, tokenIndex6
								if buffer[position] != rune('-') {
									goto l4
								}
								position++
							}
						l6:
							goto l5
						l4:
							position, tokenIndex = position4, tokenIndex4
						}
					l5:
						{
							position8, tokenIndex8 := position, tokenIndex
							if buffer[position] != rune('0') {
								goto l9
							}
							position++
							{
								position10, tokenIndex10 := position, tokenIndex
								if buffer[position] != rune('x') {
									goto l11
								}
								position++
								goto l10
							l11:
								position, tokenIndex = position10, tokenIndex10
								if buffer[position] != rune('X') {
									goto l9
								}
								position++
							}
						l10:
							{
								position12 := position
								{
									position13, tokenIndex13 := position, tokenIndex
									if !_rules[ruleHexDigit]() {
										goto l14
									}
								l15:
									{
										position16, tokenIndex16 := position, tokenIndex
									l17:
										{
											position18, tokenIndex18 := position, tokenIndex
											if buffer[position] != rune('_') {
												goto l18
											}
											position++
											goto l17
										l18:
											position, tokenIndex = position18, tokenIndex18
										}
										if !_rules[ruleHexDigit]() {
											goto l16
										}
										goto l15
									l16:
										position, tokenIndex = position16, tokenIndex16
									}
									goto l13
								l14:
									position, tokenIndex = position13, tokenIndex13
									if buffer[position] != rune('0') {
										goto l9
									}
									position++
								}
							l13:
								add(ruleHexNumeral, position12)
							}
							goto l8
						l9:
							position, tokenIndex = position8, tokenIndex8
							{
								position19 := position
								{
									position20, tokenIndex20 := position, tokenIndex
									if c := buffer[position]; c < rune('1') || c > rune('9') {
										goto l21
									}
									position++
								l22:
									{
										position23, tokenIndex23 := position, tokenIndex
									l24:
										{
											position25, tokenIndex25 := position, tokenIndex
											if buffer[position] != rune('_') {
												goto l25
											}
											position++
											goto l24
										l25:
											position, tokenIndex = position25, tokenIndex25
										}
										if c := buffer[position]; c < rune('0') || c > rune('9') {
											goto l23
										}
										position++
										goto l22
									l23:
										position, tokenIndex = position23, tokenIndex23
									}
									goto l20
								l21:
									position, tokenIndex = position20, tokenIndex20
									if buffer[position] != rune('0') {
										goto l0
									}
									position++
								}
							l20:
								add(ruleDecimalNumeral, position19)
							}
						}
					l8:
						{
							position26, tokenIndex26 := position, tokenIndex
							{
								position28, tokenIndex28 := position, tokenIndex
								if buffer[position] != rune('u') {
									goto l29
								}
								position++
								goto l28
							l29:
								position, tokenIndex = position28, tokenIndex28
								if buffer[position] != rune('U') {
									goto l26
								}
								position++
							}
						l28:
							goto l27
						l26:
							position, tokenIndex = position26, tokenIndex26
						}
					l27:
						add(ruleIntegerLiteral, position3)
					}
					add(ruleValue, position2)
				}
				{
					position30 := position
					{
						position31, tokenIndex31 := position, tokenIndex
						if !matchDot() {
							goto l31
						}
						goto l0
					l31:
						position, tokenIndex = position31, tokenIndex31
					}
					add(ruleEOF, position30)
				}
				add(ruleScript, position1)
			}
			return true
		l0:
			position, tokenIndex = position0, tokenIndex0
			return false
		},
		/* 1 EOF <- <!.> */
		nil,
		/* 2 Value <- <IntegerLiteral> */
		nil,
		/* 3 IntegerLiteral <- <(('+' / '-')? (('0' ('x' / 'X') HexNumeral) / DecimalNumeral) ('u' / 'U')?)> */
		nil,
		/* 4 HexNumeral <- <((HexDigit ('_'* HexDigit)*) / '0')> */
		nil,
		/* 5 HexDigit <- <((&('a' | 'b' | 'c' | 'd' | 'e' | 'f') [a-f]) | (&('A' | 'B' | 'C' | 'D' | 'E' | 'F') [A-F]) | (&('0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9') [0-9]))> */
		func() bool {
			position36, tokenIndex36 := position, tokenIndex
			{
				position37 := position
				{
					switch buffer[position] {
					case 'a', 'b', 'c', 'd', 'e', 'f':
						if c := buffer[position]; c < rune('a') || c > rune('f') {
							goto l36
						}
						position++
					case 'A', 'B', 'C', 'D', 'E', 'F':
						if c := buffer[position]; c < rune('A') || c > rune('F') {
							goto l36
						}
						position++
					default:
						if c := buffer[position]; c < rune('0') || c > rune('9') {
							goto l36
						}
						position++
					}
				}

				add(ruleHexDigit, position37)
			}
			return true
		l36:
			position, tokenIndex = position36, tokenIndex36
			return false
		},
		/* 6 DecimalNumeral <- <(([1-9] ('_'* [0-9])*) / '0')> */
		nil,
	}
	p.rules = _rules
	return nil
}
